collections_config:
  posts:
    path: content/blog
    output: true
    url: /blog/[slug]/
    _enabled_editors:
      - content
  pages:
    path: content/pages
    output: true
    url: /[slug]/
    _enabled_editors:
      - visual
